language: rust
script: cargo build --verbose --package $PACKAGE --no-default-features --features="$FEATURES"
matrix:
  include:
    - name: "OSX Game Only"
      rust: nightly
      os: osx
      env: PACKAGE="minimum-demo" FEATURES="metal"
    - name: "OSX Editor"
      rust: nightly
      os: osx
      env: PACKAGE="minimum-demo" FEATURES="metal editor"
    - name: "Linux Editor"
      rust: nightly
      os: linux
      env: PACKAGE="minimum-demo" FEATURES="vulkan editor"
    - name: "Windows Editor"
      rust: nightly
      os: windows
      env: PACKAGE="minimum-demo" FEATURES="dx12 editor"
    - name: "OSX Base"
      rust: nightly
      os: osx
      env: PACKAGE="minimum" FEATURES=""
    - name: "Linux Base"
      rust: nightly
      os: linux
      env: PACKAGE="minimum" FEATURES=""
    - name: "Windows Base"
      rust: nightly
      os: window
      env: PACKAGE="minimum" FEATURES=""
  fast_finish: true