cargo-features = ["profile-overrides"]


[workspace]

members = [
    "minimum",
    "minimum-derive",
    "minimum-examples",
    "minimum-demo"
]

exclude = [
    "minimum-examples",
    "minimum-demo"
]

[patch.crates-io]

rendy = { git = 'https://github.com/aclysma/rendy.git', branch="winit-0.20.0" }
gfx-hal = { git = 'https://github.com/aclysma/gfx.git', branch="winit-0.20.0" }
gfx-backend-metal = { git = 'https://github.com/aclysma/gfx.git', branch="winit-0.20.0" }
imgui = { git = 'https://github.com/aclysma/imgui-rs.git' }
imgui-winit-support = { git = 'https://github.com/aclysma/imgui-rs.git' }


[profile.dev]
opt-level = 0
debug = true

#[profile.dev.overrides.nalgebra]
#opt-level = 3
#
#[profile.dev.overrides.nalgebra-glm]
#opt-level = 3
#
#[profile.dev.overrides.nphysics2d]
#opt-level = 3
#
#[profile.dev.overrides.ncollide2d]
#opt-level = 3

[profile.dev.overrides."*"]
opt-level = 3
