#cargo-features = ["profile-overrides"]


[workspace]

members = [
    "minimum-base",
    "minimum-framework",
    "minimum-examples",
    "minimum-demo",
    "minimum"
]

exclude = [
    "minimum-examples",
    "minimum-demo"
]

[patch.crates-io]

#[profile.dev]
#opt-level = 0
#debug = true

#[profile.dev.overrides."*"]
#opt-level = 3
