[package]
name = "minimum-examples"
version = "0.0.0"
authors = ["Philip Degarmo <aclysma@gmail.com>"]
edition = "2018"
publish = false

[features]

[dev-dependencies]
minimum = { path = "../minimum", features = ["std"] }
